import { z } from "zod";

export const FavoriteCategory = z.enum(["model", "provider", "software", "subscription"]);
export type FavoriteCategory = z.infer<typeof FavoriteCategory>;
export const FAVORITE_CATEGORIES: Record<FavoriteCategory, string> = {
  model: "Models",
  provider: "Providers",
  software: "Agent software",
  subscription: "Subscriptions",
};
export interface FavoriteOption {
  id: string;
  category: FavoriteCategory;
  label: string;
  icon: string | null;
  aliases: string;
}
// Model families stay useful as individual model versions change.
export const FAVORITE_OPTIONS: FavoriteOption[] = [
  {
    id: "model:codex",
    category: "model",
    label: "Codex",
    icon: "/providers/codex.svg",
    aliases: "",
  },
  {
    id: "model:gpt",
    category: "model",
    label: "GPT",
    icon: "/providers/codex.svg",
    aliases: "",
  },
  {
    id: "model:claude",
    category: "model",
    label: "Claude",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "model:claude-opus",
    category: "model",
    label: "Claude Opus",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "model:claude-sonnet",
    category: "model",
    label: "Claude Sonnet",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "model:claude-haiku",
    category: "model",
    label: "Claude Haiku",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "model:glm",
    category: "model",
    label: "GLM",
    icon: "/providers/zai.svg",
    aliases: "Zhipu Z.ai",
  },
  {
    id: "model:deepseek",
    category: "model",
    label: "DeepSeek",
    icon: "/providers/deepseek.svg",
    aliases: "",
  },
  {
    id: "model:gemini",
    category: "model",
    label: "Gemini",
    icon: "/providers/gemini.svg",
    aliases: "",
  },
  {
    id: "model:gemini-pro",
    category: "model",
    label: "Gemini Pro",
    icon: "/providers/gemini.svg",
    aliases: "",
  },
  {
    id: "model:gemini-flash",
    category: "model",
    label: "Gemini Flash",
    icon: "/providers/gemini.svg",
    aliases: "",
  },
  {
    id: "model:grok",
    category: "model",
    label: "Grok",
    icon: "/providers/grok.svg",
    aliases: "",
  },
  {
    id: "model:qwen",
    category: "model",
    label: "Qwen",
    icon: "/providers/alibaba.svg",
    aliases: "",
  },
  {
    id: "model:llama",
    category: "model",
    label: "Llama",
    icon: null,
    aliases: "",
  },
  {
    id: "model:mistral",
    category: "model",
    label: "Mistral",
    icon: "/providers/mistral.svg",
    aliases: "",
  },
  {
    id: "model:codestral",
    category: "model",
    label: "Codestral",
    icon: "/providers/mistral.svg",
    aliases: "",
  },
  {
    id: "model:kimi",
    category: "model",
    label: "Kimi",
    icon: "/providers/kimi.svg",
    aliases: "Moonshot",
  },
  {
    id: "model:minimax",
    category: "model",
    label: "MiniMax",
    icon: "/providers/minimax.svg",
    aliases: "",
  },
  {
    id: "model:devstral",
    category: "model",
    label: "Devstral",
    icon: "/providers/mistral.svg",
    aliases: "",
  },
  {
    id: "model:command",
    category: "model",
    label: "Command",
    icon: null,
    aliases: "",
  },
  {
    id: "model:nova",
    category: "model",
    label: "Nova",
    icon: "/providers/bedrock.svg",
    aliases: "",
  },
  {
    id: "model:phi",
    category: "model",
    label: "Phi",
    icon: null,
    aliases: "",
  },
  {
    id: "model:doubao",
    category: "model",
    label: "Doubao",
    icon: "/providers/doubao.svg",
    aliases: "",
  },
  {
    id: "model:step",
    category: "model",
    label: "Step",
    icon: "/providers/stepfun.svg",
    aliases: "",
  },
  {
    id: "model:mimo",
    category: "model",
    label: "MiMo",
    icon: "/providers/mimo.svg",
    aliases: "",
  },
  {
    id: "model:composer",
    category: "model",
    label: "Composer",
    icon: "/providers/cursor.svg",
    aliases: "",
  },
  {
    id: "provider:openai",
    category: "provider",
    label: "OpenAI",
    icon: "/providers/codex.svg",
    aliases: "GPT Codex",
  },
  {
    id: "provider:anthropic",
    category: "provider",
    label: "Anthropic",
    icon: "/providers/claude.svg",
    aliases: "Claude",
  },
  {
    id: "provider:z-ai",
    category: "provider",
    label: "Z.ai",
    icon: "/providers/zai.svg",
    aliases: "Zhipu GLM",
  },
  {
    id: "provider:deepseek",
    category: "provider",
    label: "DeepSeek",
    icon: "/providers/deepseek.svg",
    aliases: "",
  },
  {
    id: "provider:google",
    category: "provider",
    label: "Google",
    icon: "/providers/gemini.svg",
    aliases: "Gemini",
  },
  {
    id: "provider:xai",
    category: "provider",
    label: "xAI",
    icon: "/providers/grok.svg",
    aliases: "",
  },
  {
    id: "provider:alibaba-cloud",
    category: "provider",
    label: "Alibaba Cloud",
    icon: "/providers/alibaba.svg",
    aliases: "",
  },
  {
    id: "provider:meta",
    category: "provider",
    label: "Meta",
    icon: null,
    aliases: "",
  },
  {
    id: "provider:mistral-ai",
    category: "provider",
    label: "Mistral AI",
    icon: "/providers/mistral.svg",
    aliases: "",
  },
  {
    id: "provider:moonshot-ai",
    category: "provider",
    label: "Moonshot AI",
    icon: "/providers/kimi.svg",
    aliases: "",
  },
  {
    id: "provider:minimax",
    category: "provider",
    label: "MiniMax",
    icon: "/providers/minimax.svg",
    aliases: "",
  },
  {
    id: "provider:cohere",
    category: "provider",
    label: "Cohere",
    icon: null,
    aliases: "",
  },
  {
    id: "provider:amazon-bedrock",
    category: "provider",
    label: "Amazon Bedrock",
    icon: "/providers/bedrock.svg",
    aliases: "",
  },
  {
    id: "provider:microsoft-azure",
    category: "provider",
    label: "Microsoft Azure",
    icon: null,
    aliases: "",
  },
  {
    id: "provider:openrouter",
    category: "provider",
    label: "OpenRouter",
    icon: "/providers/openrouter.svg",
    aliases: "",
  },
  {
    id: "provider:together-ai",
    category: "provider",
    label: "Together AI",
    icon: null,
    aliases: "",
  },
  {
    id: "provider:fireworks-ai",
    category: "provider",
    label: "Fireworks AI",
    icon: null,
    aliases: "",
  },
  {
    id: "provider:groq",
    category: "provider",
    label: "Groq",
    icon: null,
    aliases: "",
  },
  {
    id: "provider:cerebras",
    category: "provider",
    label: "Cerebras",
    icon: null,
    aliases: "",
  },
  {
    id: "provider:hugging-face",
    category: "provider",
    label: "Hugging Face",
    icon: null,
    aliases: "",
  },
  {
    id: "provider:ollama",
    category: "provider",
    label: "Ollama",
    icon: "/providers/ollama.svg",
    aliases: "",
  },
  {
    id: "provider:vertex-ai",
    category: "provider",
    label: "Vertex AI",
    icon: "/providers/vertexai.svg",
    aliases: "",
  },
  {
    id: "provider:perplexity",
    category: "provider",
    label: "Perplexity",
    icon: "/providers/perplexity.svg",
    aliases: "",
  },
  {
    id: "provider:venice",
    category: "provider",
    label: "Venice",
    icon: "/providers/venice.svg",
    aliases: "",
  },
  {
    id: "provider:synthetic",
    category: "provider",
    label: "Synthetic",
    icon: "/providers/synthetic.svg",
    aliases: "",
  },
  {
    id: "software:paseo",
    category: "software",
    label: "Paseo",
    icon: "/agent-software/paseo.svg",
    aliases: "Passio orchestration control center",
  },
  {
    id: "software:orca",
    category: "software",
    label: "Orca",
    icon: "/agent-software/orca.png",
    aliases: "",
  },
  {
    id: "software:codex-app",
    category: "software",
    label: "Codex app",
    icon: "/providers/codex.svg",
    aliases: "OpenAI desktop orchestration",
  },
  {
    id: "software:claude-app",
    category: "software",
    label: "Claude app",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "software:claude-cli",
    category: "software",
    label: "Claude CLI",
    icon: "/providers/claude.svg",
    aliases: "Claude Code terminal",
  },
  {
    id: "software:codex-cli",
    category: "software",
    label: "Codex CLI",
    icon: "/providers/codex.svg",
    aliases: "",
  },
  {
    id: "software:chatgpt",
    category: "software",
    label: "ChatGPT",
    icon: "/providers/codex.svg",
    aliases: "",
  },
  {
    id: "software:gemini-cli",
    category: "software",
    label: "Gemini CLI",
    icon: "/providers/gemini.svg",
    aliases: "",
  },
  {
    id: "software:opencode",
    category: "software",
    label: "OpenCode",
    icon: "/providers/opencode.svg",
    aliases: "",
  },
  {
    id: "software:cursor",
    category: "software",
    label: "Cursor",
    icon: "/providers/cursor.svg",
    aliases: "",
  },
  {
    id: "software:windsurf",
    category: "software",
    label: "Windsurf",
    icon: "/providers/windsurf.svg",
    aliases: "",
  },
  {
    id: "software:github-copilot",
    category: "software",
    label: "GitHub Copilot",
    icon: "/providers/copilot.svg",
    aliases: "",
  },
  {
    id: "software:antigravity",
    category: "software",
    label: "Antigravity",
    icon: "/providers/antigravity.svg",
    aliases: "",
  },
  {
    id: "software:cline",
    category: "software",
    label: "Cline",
    icon: null,
    aliases: "",
  },
  {
    id: "software:roo-code",
    category: "software",
    label: "Roo Code",
    icon: null,
    aliases: "",
  },
  {
    id: "software:kilo-code",
    category: "software",
    label: "Kilo Code",
    icon: "/providers/kilo.svg",
    aliases: "",
  },
  {
    id: "software:aider",
    category: "software",
    label: "Aider",
    icon: null,
    aliases: "",
  },
  {
    id: "software:continue",
    category: "software",
    label: "Continue",
    icon: null,
    aliases: "",
  },
  {
    id: "software:amp",
    category: "software",
    label: "Amp",
    icon: "/providers/amp.svg",
    aliases: "",
  },
  {
    id: "software:factory",
    category: "software",
    label: "Droid / Factory",
    icon: "/providers/factory.svg",
    aliases: "",
  },
  {
    id: "software:goose",
    category: "software",
    label: "Goose",
    icon: null,
    aliases: "",
  },
  {
    id: "software:openhands",
    category: "software",
    label: "OpenHands",
    icon: null,
    aliases: "",
  },
  {
    id: "software:conductor",
    category: "software",
    label: "Conductor",
    icon: null,
    aliases: "",
  },
  {
    id: "software:claude-squad",
    category: "software",
    label: "Claude Squad",
    icon: null,
    aliases: "",
  },
  {
    id: "software:openclaw",
    category: "software",
    label: "OpenClaw",
    icon: null,
    aliases: "",
  },
  {
    id: "software:warp",
    category: "software",
    label: "Warp",
    icon: "/providers/warp.svg",
    aliases: "",
  },
  {
    id: "software:zed",
    category: "software",
    label: "Zed",
    icon: null,
    aliases: "",
  },
  {
    id: "software:jetbrains-junie",
    category: "software",
    label: "JetBrains Junie",
    icon: "/providers/jetbrains.svg",
    aliases: "",
  },
  {
    id: "software:kiro",
    category: "software",
    label: "Kiro",
    icon: "/providers/kiro.svg",
    aliases: "",
  },
  {
    id: "software:augment",
    category: "software",
    label: "Augment",
    icon: "/providers/augment.svg",
    aliases: "",
  },
  {
    id: "software:codebuff",
    category: "software",
    label: "Codebuff",
    icon: "/providers/codebuff.svg",
    aliases: "",
  },
  {
    id: "software:manus",
    category: "software",
    label: "Manus",
    icon: "/providers/manus.svg",
    aliases: "",
  },
  {
    id: "software:lm-studio",
    category: "software",
    label: "LM Studio",
    icon: null,
    aliases: "",
  },
  {
    id: "software:proprietary",
    category: "software",
    label: "Proprietary",
    icon: "/agent-software/proprietary.svg",
    aliases: "",
  },
  {
    id: "subscription:chatgpt-plus",
    category: "subscription",
    label: "ChatGPT Plus",
    icon: "/providers/codex.svg",
    aliases: "",
  },
  {
    id: "subscription:chatgpt-pro",
    category: "subscription",
    label: "ChatGPT Pro",
    icon: "/providers/codex.svg",
    aliases: "",
  },
  {
    id: "subscription:chatgpt-business",
    category: "subscription",
    label: "ChatGPT Business",
    icon: "/providers/codex.svg",
    aliases: "",
  },
  {
    id: "subscription:chatgpt-enterprise",
    category: "subscription",
    label: "ChatGPT Enterprise",
    icon: "/providers/codex.svg",
    aliases: "",
  },
  {
    id: "subscription:claude-pro",
    category: "subscription",
    label: "Claude Pro",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "subscription:claude-max",
    category: "subscription",
    label: "Claude Max",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "subscription:claude-team",
    category: "subscription",
    label: "Claude Team",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "subscription:claude-enterprise",
    category: "subscription",
    label: "Claude Enterprise",
    icon: "/providers/claude.svg",
    aliases: "",
  },
  {
    id: "subscription:google-ai-plus",
    category: "subscription",
    label: "Google AI Plus",
    icon: "/providers/gemini.svg",
    aliases: "",
  },
  {
    id: "subscription:google-ai-pro",
    category: "subscription",
    label: "Google AI Pro",
    icon: "/providers/gemini.svg",
    aliases: "",
  },
  {
    id: "subscription:google-ai-ultra",
    category: "subscription",
    label: "Google AI Ultra",
    icon: "/providers/gemini.svg",
    aliases: "",
  },
  {
    id: "subscription:cursor-pro",
    category: "subscription",
    label: "Cursor Pro",
    icon: "/providers/cursor.svg",
    aliases: "",
  },
  {
    id: "subscription:cursor-pro-plus",
    category: "subscription",
    label: "Cursor Pro+",
    icon: "/providers/cursor.svg",
    aliases: "",
  },
  {
    id: "subscription:cursor-ultra",
    category: "subscription",
    label: "Cursor Ultra",
    icon: "/providers/cursor.svg",
    aliases: "",
  },
  {
    id: "subscription:cursor-teams",
    category: "subscription",
    label: "Cursor Teams",
    icon: "/providers/cursor.svg",
    aliases: "",
  },
  {
    id: "subscription:github-copilot-pro",
    category: "subscription",
    label: "GitHub Copilot Pro",
    icon: "/providers/copilot.svg",
    aliases: "",
  },
  {
    id: "subscription:github-copilot-pro-plus",
    category: "subscription",
    label: "GitHub Copilot Pro+",
    icon: "/providers/copilot.svg",
    aliases: "",
  },
  {
    id: "subscription:github-copilot-business",
    category: "subscription",
    label: "GitHub Copilot Business",
    icon: "/providers/copilot.svg",
    aliases: "",
  },
  {
    id: "subscription:github-copilot-enterprise",
    category: "subscription",
    label: "GitHub Copilot Enterprise",
    icon: "/providers/copilot.svg",
    aliases: "",
  },
  {
    id: "subscription:windsurf-pro",
    category: "subscription",
    label: "Windsurf Pro",
    icon: "/providers/windsurf.svg",
    aliases: "",
  },
  {
    id: "subscription:perplexity-pro",
    category: "subscription",
    label: "Perplexity Pro",
    icon: "/providers/perplexity.svg",
    aliases: "",
  },
  {
    id: "subscription:perplexity-max",
    category: "subscription",
    label: "Perplexity Max",
    icon: "/providers/perplexity.svg",
    aliases: "",
  },
  {
    id: "subscription:supergrok",
    category: "subscription",
    label: "SuperGrok",
    icon: "/providers/grok.svg",
    aliases: "",
  },
  {
    id: "subscription:z-ai-coding-plan",
    category: "subscription",
    label: "Z.ai Coding Plan",
    icon: "/providers/zai.svg",
    aliases: "",
  },
  {
    id: "subscription:kimi-coding",
    category: "subscription",
    label: "Kimi Coding",
    icon: "/providers/kimi.svg",
    aliases: "",
  },
  {
    id: "subscription:minimax-coding-plan",
    category: "subscription",
    label: "MiniMax Coding Plan",
    icon: "/providers/minimax.svg",
    aliases: "",
  },
  {
    id: "subscription:opencode-go",
    category: "subscription",
    label: "OpenCode Go",
    icon: "/providers/opencodego.svg",
    aliases: "",
  },
];
const optionsById = new Map(FAVORITE_OPTIONS.map((option) => [option.id, option]));
export function favoriteOption(id: string) {
  return optionsById.get(id);
}
export const ProfileFavorite = z
  .object({
    id: z.string().max(100),
    category: FavoriteCategory,
    name: z.string().trim().min(1).max(60).optional(),
    logoUrl: z.string().url().startsWith("https://").max(500).optional(),
  })
  .superRefine((item, context) => {
    const option = favoriteOption(item.id);
    if (
      (!option || option.category !== item.category) &&
      !(item.id === `custom:${item.category}` && item.name)
    ) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Choose a known favorite or name a custom favorite",
      });
    }
  });
export type ProfileFavorite = z.infer<typeof ProfileFavorite>;
export const ProfileFavorites = z
  .array(ProfileFavorite)
  .max(40)
  .refine((items) => new Set(items.map((item) => item.id)).size === items.length, {
    message: "Favorites must be unique",
  });
